name: Run MihuBot script

on:
  issues:
    types: [opened]

jobs:
  run-windows:
    if: (github.actor == 'MihuBot' || github.actor == 'MihaZupan') && contains(github.event.issue.body, 'RUN_AS_GITHUB_ACTION_')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

      - name: Run script
        shell: pwsh
        env:
          RUNTIME_UTILS_TOKEN: ${{ secrets.RUNTIME_UTILS_TOKEN }}
        run: |
          cd Runner
          dotnet run -c Release "${{ github.event_path }}"
